setTypeShoppingPt_1_2 <- function(df) {
  df$customer_ID        <- as.character(df$customer_ID)
  df$day                <- as.factor(df$day)
  df$pt1_segmentedTime  <- as.factor(df$pt1_segmentedTime)
  df$pt1_state          <- as.factor(df$pt1_state)
  df$pt1_homeowner      <- as.factor(df$pt1_homeowner)
  df$pt1_risk_factor    <- as.factor(df$pt1_risk_factor)
  df$pt1_married_couple <- as.factor(df$pt1_married_couple)
  df$pt1_C_previous     <- as.factor(df$pt1_C_previous)
  df$pt1_A              <- as.factor(df$pt1_A)
  df$pt1_B              <- as.factor(df$pt1_B)
  df$pt1_C              <- as.factor(df$pt1_C)
  df$pt1_D              <- as.factor(df$pt1_D)
  df$pt1_E              <- as.factor(df$pt1_E)
  df$pt1_F              <- as.factor(df$pt1_F)
  df$pt1_G              <- as.factor(df$pt1_G)
  df$pt2_segmentedTime  <- as.factor(df$pt2_segmentedTime)
  df$pt2_state          <- as.factor(df$pt2_state)
  df$pt2_homeowner      <- as.factor(df$pt2_homeowner)
  df$pt2_risk_factor    <- as.factor(df$pt2_risk_factor)
  df$pt2_married_couple <- as.factor(df$pt2_married_couple)
  df$pt2_C_previous     <- as.factor(df$pt2_C_previous)
  df$pt2_A              <- as.factor(df$pt2_A)
  df$pt2_B              <- as.factor(df$pt2_B)
  df$pt2_C              <- as.factor(df$pt2_C)
  df$pt2_D              <- as.factor(df$pt2_D)
  df$pt2_E              <- as.factor(df$pt2_E)
  df$pt2_F              <- as.factor(df$pt2_F)
  df$pt2_G              <- as.factor(df$pt2_G)
  df$rt1_A              <- as.factor(df$rt1_A)
  df$rt1_B              <- as.factor(df$rt1_B)
  df$rt1_C              <- as.factor(df$rt1_C)
  df$rt1_D              <- as.factor(df$rt1_D)
  df$rt1_E              <- as.factor(df$rt1_E)
  df$rt1_F              <- as.factor(df$rt1_F)
  df$rt1_G              <- as.factor(df$rt1_G)
  return(df)
}
